title: NetSci 2025
description: International School and Conference on Network Science

# Online
baseurl: ""
url: https://NetSci2025.github.io

copyright: Place Holder
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
  - run.sh
